### PR TITLE
feat: improve Jira check

### PR DESCRIPTION
**Pull request by andrewrynhard**
Fixes a few minor issues:

- make square brackets optional
- allow for conventional commit scopes to be present

Signed-off-by: Andrew Rynhard <andrew@rynhard.io>

cc @olivernybroe @andrevalentin @flyhard

### CODE REVIEW

**Review by smira — APPROVED** [review]

**Comment by olivernybroe** [comment]
Looks great 👍  
Looking forward to this 😄

**Comment by andrevalentin** [comment]
@andrewrynhard @smira any chance this can be merged today? We are looking forward to getting these changes live. Thanks for all the good work guys 🙏

**Review by flyhard — APPROVED** [review]
Looks fine to me
/lgtm

**Review by olivernybroe — APPROVED** [review]
/lgtm

**Comment by andrewrynhard** [comment]
@andrevalentin you good with compiling for now or do we need a release?

**Comment by andrevalentin** [comment]
@andrewrynhard thanks! We are good with this, still trying to get it to work right now, seems like it won't recognise the Jira key, but we are working on some more tests before we decide that we can't get it to work :-)
Thanks for now at least!

**Comment by andrewrynhard** [comment]
@andrevalentin feel free to join our slack and ping me: https://slack.dev.talos-systems.io/

**Pull request merged**
