### PR TITLE
chore: bump golangci-lint and fix linting issues

### PR DESCRIPTION
**Pull request by alex1989hu**
chore: bump golangci-lint and fix linting issues

Signed-off-by: Alex Szakaly <alex.szakaly@gmail.com>

Note:
Copied `linter.disable` array and `golangci-lint` version from `talos` repository.

### CODE REVIEW

**Comment by smira** [comment]
@alex1989hu conform is not happy about this commit: 

image

**Comment by alex1989hu** [comment]
> @alex1989hu conform is not happy about this commit:
> 
> image

I was on lunch time when I saw that failure. I have just force pushed.

**Review by smira — APPROVED** [review]

**Comment by andrewrynhard** [comment]
Hey @alex1989hu 😄. Glad to see you using confirm too. Thanks for the PR.

**Pull request merged**
